package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

func generateHTMLReport(r Report) string {
	successRate := float64(0)
	if r.TotalRequests > 0 {
		successRate = float64(r.SuccessCount) / float64(r.TotalRequests) * 100
	}

	// 状态码数据
	var statusLabels, statusValues []string
	codes := make([]int, 0, len(r.StatusCodes))
	for code := range r.StatusCodes {
		codes = append(codes, code)
	}
	sort.Ints(codes)
	for _, code := range codes {
		statusLabels = append(statusLabels, fmt.Sprintf(`"%d"`, code))
		statusValues = append(statusValues, fmt.Sprintf(`"%d"`, r.StatusCodes[code]))
	}

	// 错误列表
	var errorRows strings.Builder
	for errMsg, count := range r.Errors {
		errorRows.WriteString(fmt.Sprintf(
			`<tr><td class="px-4 py-2 text-red-400">%d</td><td class="px-4 py-2 text-gray-300">%s</td></tr>`,
			count, errMsg,
		))
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>负载测试报告 - %s</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
body { background: #0f172a; color: #e2e8f0; font-family: 'SF Mono', 'Fira Code', monospace; margin: 0; padding: 20px; }
.container { max-width: 960px; margin: 0 auto; }
h1 { color: #38bdf8; border-bottom: 2px solid #1e293b; padding-bottom: 16px; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 24px 0; }
.card { background: #1e293b; border-radius: 12px; padding: 20px; text-align: center; }
.card .value { font-size: 2rem; font-weight: bold; }
.card .label { color: #94a3b8; font-size: 0.85rem; margin-top: 4px; }
.green { color: #4ade80; }
.yellow { color: #facc15; }
.red { color: #f87171; }
.cyan { color: #38bdf8; }
table { width: 100%%; border-collapse: collapse; margin: 16px 0; }
th { background: #1e293b; padding: 12px; text-align: left; color: #94a3b8; }
td { padding: 8px 12px; border-bottom: 1px solid #1e293b; }
.chart-container { background: #1e293b; border-radius: 12px; padding: 20px; margin: 16px 0; }
.meta { color: #64748b; font-size: 0.85rem; margin-bottom: 24px; }
</style>
</head>
<body>
<div class="container">
<h1>Load Test Report</h1>
<p class="meta">URL: %s | Concurrency: %d | Duration: %s | Generated at %s</p>

<div class="grid">
  <div class="card">
    <div class="value cyan">%.0f</div>
    <div class="label">RPS (Requests/sec)</div>
  </div>
  <div class="card">
    <div class="value green">%.1f%%</div>
    <div class="label">Success Rate</div>
  </div>
  <div class="card">
    <div class="value yellow">%s</div>
    <div class="label">Mean Latency</div>
  </div>
  <div class="card">
    <div class="value">%d</div>
    <div class="label">Total Requests</div>
  </div>
</div>

<h2>Latency Percentiles</h2>
<table>
<tr><th>Percentile</th><th>Latency</th></tr>
%s
</table>

<div class="chart-container">
  <canvas id="statusChart" height="100"></canvas>
</div>

%s

<footer style="text-align:center;color:#475569;margin-top:40px;">
  Generated by load-tester | %s
</footer>
</div>

<script>
new Chart(document.getElementById('statusChart'), {
  type: 'bar',
  data: {
    labels: [%s],
    datasets: [{
      label: 'Status Codes',
      data: [%s],
      backgroundColor: ['#4ade80','#38bdf8','#facc15','#f87171','#a78bfa']
    }]
  },
  options: {
    responsive: true,
    plugins: { legend: { display: false } },
    scales: { y: { beginAtZero: true, ticks: { color: '#94a3b8' }, grid: { color: '#334155' } }, x: { ticks: { color: '#94a3b8' }, grid: { color: '#334155' } } }
  }
});
</script>
</body>
</html>`,
		r.URL,
		r.URL, r.Concurrency, r.TestDuration.Round(time.Millisecond), time.Now().Format("2006-01-02 15:04:05"),
		r.RPS,
		successRate,
		r.MeanLatency.Round(time.Microsecond),
		r.TotalRequests,
		generatePercentileRows(r),
		generateErrorSection(errorRows.String()),
		time.Now().Format("2006-01-02 15:04:05"),
		strings.Join(statusLabels, ","),
		strings.Join(statusValues, ","),
	)

	return html
}

func generatePercentileRows(r Report) string {
	var rows strings.Builder
	for _, p := range []float64{50, 75, 90, 95, 99} {
		if d, ok := r.Percentiles[p]; ok {
			color := "green"
			if d > 500*time.Millisecond {
				color = "red"
			} else if d > 100*time.Millisecond {
				color = "yellow"
			}
			rows.WriteString(fmt.Sprintf(
				`<tr><td class="px-4 py-2">P%.0f</td><td class="%s px-4 py-2">%s</td></tr>`,
				p, color, d.Round(time.Microsecond),
			))
		}
	}
	return rows.String()
}

func generateErrorSection(errorRows string) string {
	if errorRows == "" {
		return ""
	}
	return fmt.Sprintf(`
<h2 class="red">Errors</h2>
<table>
<tr><th>Count</th><th>Error</th></tr>
%s
</table>`, errorRows)
}
